---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check Elasticsearch can running
    command:
      cmd: "elasticsearch --version"
    environment:
      PATH: "$PATH:{{ elastic_home }}/bin"
    changed_when: false
